const relationshipToPatientOptions: any = {
  1: 'Self',
  2: 'Spouse',
  3: 'Child',
  4: 'Other',
  5: 'Grandparent',
  6: 'Grandchild',
  7: 'Nephew or Niece',
  9: 'Foster Child',
  10: 'Ward',
  11: 'Stepson or Stepdaughter',
  12: 'Employee',
  13: 'Unknown',
  14: 'Handicapped Dependent',
  15: 'Sponsored Dependent',
  16: 'Dependent of a Minor Dependent',
  17: 'Significant Other',
  18: 'Mother',
  19: 'Father',
  21: 'Emancipated Minor',
  22: 'Organ Donor',
  23: 'Cadaver Donor',
  24: 'Injured Plaintiff',
  25: 'Child (Ins. not Financially Respons.)',
  26: 'Life Partner',
  27: "Child (Mother's Insurance)",
  28: "Child (Father's Insurance)",
  29: 'Child (of Mother, Ins. not Financially Respons.)',
  30: 'Child (of Father, Ins. not Financially Respons.)',
  31: "Stepson or Stepdaughter (Stepmother's Insurance)",
  32: "Stepson or Stepdaughter (Stepfather's Insurance)",
};

export default relationshipToPatientOptions;
