export const patientGoalTaskGroup: string;
export const patientGoal: string;
export const patientGoalHeaderRow: string;
export const patientGoalNumber: string;
export const patientGoalUpdatedDetails: string;
export const patientGoalUpdatedDetailsLabel: string;
export const patientGoalUpdatedDetailsDate: string;
export const patientGoalTitle: string;
export const inactive: string;
