web: yarn run start
consume-computed-fields: yarn run consume:computed-fields:production
consume-member-attribution: yarn run consume:member-attribution:production
consume-scheduling: yarn run consume:scheduling:production
consume-voicemail: yarn run consume:voicemail:production
consume-phone-call: yarn run consume:phone-call:production
consume-mattermost: yarn run consume:mattermost:production
consume-task-event: yarn run consume:task-event:production
consume-contact-update: yarn run consume:contact-update:production
consume-previous-contact: yarn run consume:previous-contact:production
cron: exec supercronic /app/crontab