export const medication: string;
export const selected: string;
export const medicationRow: string;
export const medicationDetails: string;
export const medicationRowTitle: string;
export const medicationDetailsRow: string;
export const medicationInstructions: string;
export const medicationDetailsTitle: string;
export const medicationDetailsInfo: string;
