version: 2
jobs:
  lint:
    working_directory: ~/repo
    docker:
      - image: node:8.11.3@sha256:98755b9281c251f9e712069978975181a9d9b43efcbe0f2270ff6206ebc86dda
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ arch }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-
      - run: yarn install
      - save_cache:
          key: v3-dependencies-{{ arch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn lint
      - run: yarn stylelint
      - run: yarn typecheck
      - run:
          name: check-schema
          command: './scripts/check-schema-in-sync.sh'
      - run: yarn codegen
      - run: yarn danger ci

  test_frontend:
    working_directory: ~/repo
    docker:
      - image: node:8.11.3@sha256:98755b9281c251f9e712069978975181a9d9b43efcbe0f2270ff6206ebc86dda
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ arch }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-
      - run: yarn install
      - save_cache:
          key: v3-dependencies-{{ arch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn test:frontend

  test_api:
    working_directory: ~/repo
    docker:
      - image: node:8.11.3@sha256:98755b9281c251f9e712069978975181a9d9b43efcbe0f2270ff6206ebc86dda
      - image: postgres:10.4@sha256:e033c99282a81622b1eed36b735034e10d633a34cca3387f6142381770cfbcc8
        environment:
          POSTGRES_DB: commons_test
          POSTGRES_USER: root
          POSTGRES_PASSWORD: ""
      - image: redis:4.0.9@sha256:fc13b47aca9b5b53f625efe91bcd5cc44c637e80a81e5b223d5a98a6eac7ceb2
    steps:
      - checkout
      - run: apt-get update && apt-get install -y sudo
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - restore_cache:
          keys:
            - v3-dependencies-{{ arch }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-
      - run: yarn install
      - save_cache:
          key: v3-dependencies-{{ arch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for Redis
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run: yarn test:api

  test_models:
    working_directory: ~/repo
    docker:
      - image: node:8.11.3@sha256:98755b9281c251f9e712069978975181a9d9b43efcbe0f2270ff6206ebc86dda
      - image: postgres:10.4@sha256:e033c99282a81622b1eed36b735034e10d633a34cca3387f6142381770cfbcc8
        environment:
          POSTGRES_DB: commons_test
          POSTGRES_USER: root
          POSTGRES_PASSWORD: ""
      - image: redis:4.0.9@sha256:fc13b47aca9b5b53f625efe91bcd5cc44c637e80a81e5b223d5a98a6eac7ceb2
    steps:
      - checkout
      - run: apt-get update && apt-get install -y sudo
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - restore_cache:
          keys:
            - v3-dependencies-{{ arch }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-
      - run: yarn install
      - save_cache:
          key: v3-dependencies-{{ arch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for Redis
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run: yarn test:models

  deploy_staging:
    working_directory: ~/repo
    docker:
      - image: node:8.11.3@sha256:98755b9281c251f9e712069978975181a9d9b43efcbe0f2270ff6206ebc86dda
    steps:
      - checkout
      - run:
          name: known-hosts
          command: ssh-keyscan -H beta.aptible.com >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "41:eb:14:fe:32:9c:da:a5:fa:3c:3b:c4:69:18:a8:fd"
      - run:
          name: deploy
          command: git push git@beta.aptible.com:cityblock-health/commons-staging.git $CIRCLE_SHA1:master

  deploy_production:
    working_directory: ~/repo
    docker:
      - image: node:8.11.3@sha256:98755b9281c251f9e712069978975181a9d9b43efcbe0f2270ff6206ebc86dda
    steps:
      - checkout
      - run:
          name: known-hosts
          command: ssh-keyscan -H beta.aptible.com >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "41:eb:14:fe:32:9c:da:a5:fa:3c:3b:c4:69:18:a8:fd"
      - run:
          name: deploy
          command: git push git@beta.aptible.com:cityblock-health-phi-ready/commons-production.git $CIRCLE_SHA1:master

workflows:
  version: 2

  test_and_deploy:
    jobs:
      - lint:
          context: commons
          filters:
            tags:
              only: /.*/
            branches:
              ignore: master
      - test_frontend:
          filters:
            tags:
              only: /.*/
      - test_api:
          filters:
            tags:
              only: /.*/
      - test_models:
          filters:
            tags:
              only: /.*/
      - deploy_staging:
          requires:
            - lint
            - test_frontend
            - test_api
            - test_models
          filters:
            branches:
              only: master
      - deploy_production:
          requires:
            - lint
            - test_frontend
            - test_api
            - test_models
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
