export const container: string;
export const header: string;
export const fullScreen: string;
export const listItem: string;
export const title: string;
export const text: string;
export const icon: string;
export const button: string;
export const red: string;
