export default [
  {
    roles: ['familyMember'],
    allows: [],
  },
  {
    roles: ['healthCoach'],
    allows: [
      {
        resources: [
          'patient',
          'user',
          'clinic',
          'patientAnswer',
          'appointment',
          'careTeam',
          'progressNote',
        ],
        permissions: ['edit', 'view', 'delete'],
      },
    ],
  },
  {
    roles: ['physician', 'nurseCareManager'],
    allows: [
      {
        resources: ['user'],
        permissions: ['view', 'create', 'edit'],
      },
      {
        resources: [
          'patient',
          'clinic',
          'patientAnswer',
          'appointment',
          'patientTaskSuggestion',
          'careTeam',
          'progressNote',
          'quickCall',
        ],
        permissions: ['edit', 'view', 'delete', 'create'],
      },
    ],
  },
  {
    roles: ['healthCoach', 'physician', 'nurseCareManager'],
    allows: [
      {
        resources: [
          'answer',
          'concern',
          'goalSuggestionTemplate',
          'patientConcern',
          'patientGoal',
          'patientScreeningToolSubmission',
          'question',
          'questionCondition',
          'riskArea',
          'screeningTool',
        ],
        permissions: ['view'],
      },
      {
        resources: [
          'carePlanSuggestion',
          'careTeam',
          'goalSuggestion',
          'patientConcern',
          'patientTaskSuggestion',
          'taskSuggestion',
          'patientGoal',
          'progressNote',
          'quickCall',
          'task',
        ],
        permissions: ['view', 'create', 'edit', 'delete'],
      },
    ],
  },
  {
    roles: ['admin'],
    allows: [
      {
        resources: [
          'patient',
          'user',
          'careTeam',
          'allUsers',
          'clinic',
          'task',
          'appointment',
          'answer',
          'patientAnswer',
          'riskArea',
          'questionCondition',
          'question',
          'concern',
          'patientConcern',
          'carePlanSuggestion',
          'goalSuggestion',
          'goalSuggestionTemplate',
          'patientGoal',
          'taskTemplate',
          'taskSuggestion',
          'patientTaskSuggestion',
          'screeningTool',
          'patientScreeningToolSubmission',
          'progressNote',
          'progressNoteTemplate',
          'quickCall',
        ],
        permissions: ['edit', 'view', 'delete', 'create'],
      },
    ],
  },
];
