import {
  builderResources,
  careTeamMemberResources,
  patientAllActionsAllowedResources,
  patientCreatableAndDeletableOnlyResoruces,
  patientCreatableOnlyResources,
  patientNotDeletableResources,
  patientViewOnlyResources,
  userResources,
} from './resource-group';

export default [
  {
    roles: ['familyMember'],
    allows: [],
  },
  {
    roles: ['healthCoach'],
    allows: [
      {
        resources: [
          'patient',
          'user',
          'clinic',
          'patientAnswer',
          'patientScreeningToolSubmission',
          'riskAreaAssessmentSubmission',
          'appointment',
          'careTeam',
          'progressNote',
        ],
        permissions: ['edit', 'view', 'delete'],
      },
    ],
  },
  {
    roles: ['physician', 'nurseCareManager'],
    allows: [
      {
        resources: ['user'],
        permissions: ['view', 'create', 'edit'],
      },
      {
        resources: [
          'patient',
          'clinic',
          'patientAnswer',
          'patientScreeningToolSubmission',
          'riskAreaAssessmentSubmission',
          'appointment',
          'patientTaskSuggestion',
          'careTeam',
          'progressNote',
          'quickCall',
        ],
        permissions: ['edit', 'view', 'delete', 'create'],
      },
    ],
  },
  {
    roles: ['healthCoach', 'physician', 'nurseCareManager'],
    allows: [
      {
        resources: [
          'answer',
          'concern',
          'goalSuggestionTemplate',
          'patientConcern',
          'patientGoal',
          'question',
          'questionCondition',
          'riskAreaGroup',
          'riskArea',
          'screeningTool',
          'patientList',
          'CBOCategory',
          'CBO',
        ],
        permissions: ['view'],
      },
      {
        resources: [
          'carePlanSuggestion',
          'careTeam',
          'goalSuggestion',
          'patientConcern',
          'patientTaskSuggestion',
          'patientAnswer',
          'patientScreeningToolSubmission',
          'riskAreaAssessmentSubmission',
          'taskSuggestion',
          'patientGoal',
          'progressNote',
          'quickCall',
          'task',
          'computedFieldFlag',
          'CBOReferral',
        ],
        permissions: ['view', 'create', 'edit', 'delete'],
      },
    ],
  },
  {
    roles: ['admin'],
    allows: [
      {
        resources: [
          'patient',
          'user',
          'careTeam',
          'allUsers',
          'clinic',
          'task',
          'appointment',
          'answer',
          'patientAnswer',
          'riskAreaGroup',
          'riskArea',
          'questionCondition',
          'question',
          'concern',
          'patientConcern',
          'carePlanSuggestion',
          'goalSuggestion',
          'goalSuggestionTemplate',
          'patientGoal',
          'taskTemplate',
          'taskSuggestion',
          'patientTaskSuggestion',
          'screeningTool',
          'patientScreeningToolSubmission',
          'riskAreaAssessmentSubmission',
          'progressNote',
          'progressNoteTemplate',
          'quickCall',
          'computedField',
          'computedFieldFlag',
          'patientList',
          'CBOCategory',
          'CBO',
          'CBOReferral',
        ],
        permissions: ['edit', 'view', 'delete', 'create'],
      },
    ],
  },
  {
    roles: ['isBuilderEnabled'],
    allows: builderResources,
    permissions: ['create', 'view', 'edit', 'delete'],
  },
  {
    roles: ['isManagerEnabled'],
    allows: userResources,
    permissions: ['create', 'view'],
  },
  {
    roles: ['canChangeUserPermissions'],
    allows: userResources,
    permissions: ['create', 'view', 'edit'],
  },
  {
    roles: ['canDeleteUsers'],
    allows: userResources,
    permissions: ['create', 'view', 'edit', 'delete'],
  },
  {
    roles: ['canBulkAssign'],
    allows: [
      { resources: ['careTeam', 'careTeamBulk'], permissions: ['create', 'view', 'delete'] },
      { resources: careTeamMemberResources, permissions: ['view'] },
    ],
  },
  {
    roles: ['canEditCareTeam'],
    allows: [
      { resources: ['careTeam'], permissions: ['create', 'view', 'delete'] },
      { resources: careTeamMemberResources, permissions: ['view'] },
    ],
  },
  {
    roles: ['canViewAllMembers', 'canViewMembersOnPanel'],
    allows: [
      { resources: patientViewOnlyResources, permissions: ['view'] },
      { resources: patientAllActionsAllowedResources, permissions: ['view'] },
      { resources: patientCreatableAndDeletableOnlyResoruces, permissions: ['view'] },
      { resources: patientCreatableOnlyResources, permissions: ['view'] },
      { resources: patientNotDeletableResources, permissions: ['view'] },
    ],
  },
  {
    roles: ['canEditAllMembers', 'canEditMembersOnPanel'],
    allows: [
      { resources: patientViewOnlyResources, permissions: ['view'] },
      {
        resources: patientAllActionsAllowedResources,
        permissions: ['create', 'view', 'edit', 'delete'],
      },
      {
        resources: patientCreatableAndDeletableOnlyResoruces,
        permissions: ['create', 'view', 'delete'],
      },
      { resources: patientCreatableOnlyResources, permissions: ['create', 'view'] },
      { resources: patientNotDeletableResources, permissions: ['create', 'view', 'edit'] },
    ],
  },
  {
    roles: ['canShowAllMembersInPatientPanel'],
    allows: ['patient'],
    permissions: ['view'],
  },
  {
    roles: ['canDisenrollPatient'],
    allows: ['patient'],
    permissions: ['view', 'disenroll'],
  },
];
