export enum PokeType {
  normal = 'normal',
  grass = 'grass',
  fire = 'fire',
  water = 'water',
  electric = 'electric',
  psychic = 'psychic',
  ghost = 'ghost',
  dark = 'dark',
  fairy = 'fairy',
  rock = 'rock',
  ground = 'ground',
  steel = 'steel',
  flying = 'flying',
  fighting = 'fighting',
  bug = 'bug',
  ice = 'ice',
  dragon = 'dragon',
  poison = 'poison'
}
