export default {
  activeConcerns: 'Total active concerns:',
  activeGoals: 'Total active goals:',
  activeTasks: 'Total active tasks:',
  assignedTo: 'Assigned to:',
  concern: 'Concern',
  documentTitle: 'Printable MAP',
  due: 'Due:',
  goal: 'Goal:',
  map: 'Member Action Plan',
  mapAbbrev: 'MAP:',
  mapInfo:
    'This is your Member Action Plan (MAP) from Cityblock, your personalized health system. This is the central document that shows all of the health goals that you and your care team are working on. This document is meant to help you track your goals and hold yourself and your care team accountable to your action plan. Your MAP is structured around concerns, goals, and tasks.\n\nConcerns: Areas we’ve identified to work on together.\n\nGoals: Measurable aims for us to reach together.\n\nTasks: Concrete interventions that will help us achieve your goals together.',
  mapSummary: 'MAP Summary:',
  noAssignee: 'No assignee',
  noCarePlan: 'You currently have no active concerns',
  noDueDate: 'No due date',
  noLead: 'No lead',
  priorityhigh: 'High-priority ',
  prioritylow: 'Low-priority ',
  prioritymedium: 'Medium-priority ',
  task: 'Task',
  careTeam: 'Care Team:',
  member: 'Member:',
};
