export default {
  activeConcerns: 'Total active concerns:',
  activeGoals: 'Total active goals:',
  activeTasks: 'Total active tasks:',
  assignedTo: 'Assigned to:',
  concern: 'Concern',
  documentTitle: 'Printable MAP',
  due: 'Due:',
  goal: 'Goal:',
  map: 'Member Action Plan',
  mapAbbrev: 'MAP:',
  mapInfo:
    'This is your Member Action Plan from Cityblock Health. porta sem malesuada magna mollis euismod. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Maecenas sed diam eget risus varius blandit sit amet non magna. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.',
  mapSummary: 'MAP Summary:',
  noAssignee: 'No assignee',
  noCarePlan: 'You currently have no active concerns',
  noDueDate: 'No due date',
  noLead: 'No lead',
  priorityhigh: 'High-priority ',
  prioritylow: 'Low-priority ',
  prioritymedium: 'Medium-priority ',
  task: 'Task',
  careTeam: 'Care Team:',
  member: 'Member:',
};
