export const tabs: string;
export const darkTabs: string;
export const tab: string;
export const selectedTab: string;
export const relativeTab: string;
export const pane: string;
export const selectedPane: string;
export const notificationBadge: string;
export const visible: string;
