
export const ROLES = [
  'substanceUseCounselor',
  'therapistMentalHealth',
  'therapistPhysical',
  'psychiatrist',
  'dialysis',
  'housingCaseManager',
  'hasaCaseManager',
  'pharmacy',
  'homeAttendant',
  'visitingNurse',
  'durableMedicalEquipment',
  'healthHomeCareManager',
  'insurancePlanCareManager',
  'otherCaseManagement',
  'formalCaregiver',
];

export const MEDICAL_SPECIALIST_ROLES = [
  'urology',
  'endocrinology',
  'ophthalmology',
  'cardiology',
  'podiatry',
  'orthopedics',
  'infectiousDisease',
  'obgyn',
  'pulmonology',
  'nephrology',
  'hepatology',
  'gastroenterology',
  'ent',
  'vascular',
  'oncology',
  'hematology',
  'dermatology',
];
