export const container: string;
export const link: string;
export const flex: string;
export const dates: string;
export const date: string;
export const detail: string;
export const greenBorder: string;
export const yellowBorder: string;
export const redBorder: string;
