export const spinner: string;
export const scroll: string;
export const body: string;
export const bodyFlex: string;
export const domains: string;
export const paddedScroll: string;
export const flex: string;
export const container: string;
export const navBar: string;
