export const container: string;
export const addFollower: string;
export const careTeam: string;
export const hidden: string;
export const careTeamMemberDetails: string;
export const careTeamAvatar: string;
export const careTeamMemberLabel: string;
export const careTeamMemberName: string;
export const careTeamMemberRole: string;
