export const header: string;
export const container: string;
export const link: string;
export const hamburger: string;
export const searchIcon: string;
export const left: string;
export const center: string;
export const right: string;
export const userInfo: string;
