export const container: string;
export const selected: string;
export const title: string;
export const followers: string;
export const follower: string;
export const assignedTo: string;
export const dateSection: string;
export const dateLabel: string;
export const dateValue: string;
